name: Test

on:
  pull_request:
    branches:
      - "master"

jobs:
  test-go:
    name: Test Go Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make test
  validate-helm:
    name: Validate Helm Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: helm lint ./charts/ --strict
